on:
  workflow_dispatch:
    inputs:
      fbsVer:
        required: true
        type: string
      febioVer:
        required: true
        type: string
jobs:
  call_workflow:
    uses: febiosoftware/febio-workflows/.github/workflows/linux-release.yml@ci/releaseWorkflow
    with:
      febioVer: ${{inputs.febioVer}}
      fbsVer: ${{inputs.fbsVer}}
      aws-ami-id: ami-0b97a2de37c43b9ba
      aws-sg-id: sg-0ca7912782cf1538b
    secrets: inherit
