name: CI - Linux Python Module

on:
  workflow_dispatch:
  repository_dispatch:
    types: [release-published, python-module]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
jobs:
  call_workflow:
    uses: febiosoftware/febio-workflows/.github/workflows/linux-reusable.yml@develop
    with:
      package-name: python-module
      python-module: true
      publish: true
      aws-ami-id: ${{ vars.LINUX_AMI }}
      build-script: buildPython.sh
    secrets: inherit
