on:
  push:
    branches: [ ci/develop ]
jobs:
  call_workflow:
    uses: febiosoftware/febio-workflows/.github/workflows/linux-reusable.yml@develop
    with:
      aws-ami-id: ami-0b0e38d12eb5ff011
      aws-sg-id: sg-0ca7912782cf1538b
      runTests: false
      package-name: febio-studio
      requires-sdk: true
      sdk-config: |
        {
          "sdk_path": "ci/develop",
          "version": "v4.3",
        }
    secrets: inherit
