on:
  push:
    branches:
      - ci/releaseWorkflow
  workflow_dispatch:
    inputs:
      fbsVer:
        required: true
        type: string
      febioVer:
        required: true
        type: string
jobs:
  call_workflow:
    uses: febiosoftware/febio-workflows/.github/workflows/macos-release.yml@develop
    with:
      febioVer: ${{inputs.febioVer}}
      fbsVer: ${{inputs.fbsVer}}
    secrets: inherit
